version: '3'
services:
  cobot:
    build: .
    working_dir: /cobot
    ports:
      - 3000:3000
    depends_on:
      - postgres 
    environment:
      - POSTGRES_HOST=postgres
      - NODE_ENV=development
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
  postgres:
    image: postgres:11.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=web
      - POSTGRES_DB=cobot